// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/trpc': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../build/trpc/trpc/trpc').default>>>>
    }
    '/api': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../build/api/api/api').default>>>>
    }
    '/lol': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../build/lol/lol/lol').default>>>>
    }
    '/': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../$vinxi/spa/client').default>>>>
    }
  }
}
export {}